name: Go Unit Tests

on:
    push:
        branches:
            - 'main'
    pull_request:

jobs:
    run_tests:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout (GitHub)
            uses: actions/checkout@v4

          - name: Run Unit Tests
            uses: devcontainers/ci@v0.3
            with:
              imageName: emoji-data-generator-api_ci_unit_tests
              push: never
              runCmd: go test ./... -v -fullpath
